// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: protobuf/landlords.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LandlordsCreateRoomS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LandlordsCreateRoomS) Reset() {
	*x = LandlordsCreateRoomS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsCreateRoomS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsCreateRoomS) ProtoMessage() {}

func (x *LandlordsCreateRoomS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsCreateRoomS.ProtoReflect.Descriptor instead.
func (*LandlordsCreateRoomS) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{0}
}

type LandlordsCreateRoomC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间id
}

func (x *LandlordsCreateRoomC) Reset() {
	*x = LandlordsCreateRoomC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsCreateRoomC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsCreateRoomC) ProtoMessage() {}

func (x *LandlordsCreateRoomC) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsCreateRoomC.ProtoReflect.Descriptor instead.
func (*LandlordsCreateRoomC) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{1}
}

func (x *LandlordsCreateRoomC) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LandlordsJoinRoomS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间id
}

func (x *LandlordsJoinRoomS) Reset() {
	*x = LandlordsJoinRoomS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsJoinRoomS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsJoinRoomS) ProtoMessage() {}

func (x *LandlordsJoinRoomS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsJoinRoomS.ProtoReflect.Descriptor instead.
func (*LandlordsJoinRoomS) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{2}
}

func (x *LandlordsJoinRoomS) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LandlordsJoinRoomC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId       int64            `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                                                                               // 房间id
	UserIds      []string         `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                                                                                             // 玩家id
	ReadyUserIds []string         `protobuf:"bytes,3,rep,name=ready_user_ids,json=readyUserIds,proto3" json:"ready_user_ids,omitempty"`                                                                            // 已经准备的玩家
	UserSeat     map[string]int32 `protobuf:"bytes,4,rep,name=user_seat,json=userSeat,proto3" json:"user_seat,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 玩家座位
}

func (x *LandlordsJoinRoomC) Reset() {
	*x = LandlordsJoinRoomC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsJoinRoomC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsJoinRoomC) ProtoMessage() {}

func (x *LandlordsJoinRoomC) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsJoinRoomC.ProtoReflect.Descriptor instead.
func (*LandlordsJoinRoomC) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{3}
}

func (x *LandlordsJoinRoomC) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LandlordsJoinRoomC) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *LandlordsJoinRoomC) GetReadyUserIds() []string {
	if x != nil {
		return x.ReadyUserIds
	}
	return nil
}

func (x *LandlordsJoinRoomC) GetUserSeat() map[string]int32 {
	if x != nil {
		return x.UserSeat
	}
	return nil
}

type LandlordsJoinRoomNotifyC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LandlordsJoinRoomNotifyC) Reset() {
	*x = LandlordsJoinRoomNotifyC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsJoinRoomNotifyC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsJoinRoomNotifyC) ProtoMessage() {}

func (x *LandlordsJoinRoomNotifyC) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsJoinRoomNotifyC.ProtoReflect.Descriptor instead.
func (*LandlordsJoinRoomNotifyC) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{4}
}

func (x *LandlordsJoinRoomNotifyC) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LandlordsJoinRoomNotifyC) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LandlordsLeaveRoomS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LandlordsLeaveRoomS) Reset() {
	*x = LandlordsLeaveRoomS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsLeaveRoomS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsLeaveRoomS) ProtoMessage() {}

func (x *LandlordsLeaveRoomS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsLeaveRoomS.ProtoReflect.Descriptor instead.
func (*LandlordsLeaveRoomS) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{5}
}

type LandlordsLeaveRoomC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *LandlordsLeaveRoomC) Reset() {
	*x = LandlordsLeaveRoomC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsLeaveRoomC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsLeaveRoomC) ProtoMessage() {}

func (x *LandlordsLeaveRoomC) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsLeaveRoomC.ProtoReflect.Descriptor instead.
func (*LandlordsLeaveRoomC) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{6}
}

func (x *LandlordsLeaveRoomC) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LandlordsLeaveRoomNotifyC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LandlordsLeaveRoomNotifyC) Reset() {
	*x = LandlordsLeaveRoomNotifyC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsLeaveRoomNotifyC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsLeaveRoomNotifyC) ProtoMessage() {}

func (x *LandlordsLeaveRoomNotifyC) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsLeaveRoomNotifyC.ProtoReflect.Descriptor instead.
func (*LandlordsLeaveRoomNotifyC) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{7}
}

func (x *LandlordsLeaveRoomNotifyC) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LandlordsLeaveRoomNotifyC) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LandlordsStartGameS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *LandlordsStartGameS) Reset() {
	*x = LandlordsStartGameS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsStartGameS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsStartGameS) ProtoMessage() {}

func (x *LandlordsStartGameS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsStartGameS.ProtoReflect.Descriptor instead.
func (*LandlordsStartGameS) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{8}
}

func (x *LandlordsStartGameS) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LandlordsCallS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *LandlordsCallS) Reset() {
	*x = LandlordsCallS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsCallS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsCallS) ProtoMessage() {}

func (x *LandlordsCallS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsCallS.ProtoReflect.Descriptor instead.
func (*LandlordsCallS) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{9}
}

func (x *LandlordsCallS) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LandlordsPlayS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64   `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Cards  []*Card `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *LandlordsPlayS) Reset() {
	*x = LandlordsPlayS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordsPlayS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordsPlayS) ProtoMessage() {}

func (x *LandlordsPlayS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordsPlayS.ProtoReflect.Descriptor instead.
func (*LandlordsPlayS) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{10}
}

func (x *LandlordsPlayS) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LandlordsPlayS) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid  int64 `protobuf:"varint,1,opt,name=guid,proto3" json:"guid,omitempty"`   // 唯一id
	Point int32 `protobuf:"varint,2,opt,name=point,proto3" json:"point,omitempty"` // 点数
	Color int32 `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"` // 花色
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_landlords_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_landlords_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_protobuf_landlords_proto_rawDescGZIP(), []int{11}
}

func (x *Card) GetGuid() int64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *Card) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *Card) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_protobuf_landlords_proto protoreflect.FileDescriptor

var file_protobuf_landlords_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6c, 0x61, 0x6e, 0x64, 0x6c,
	0x6f, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64,
	0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x22, 0x2f, 0x0a, 0x14,
	0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x43, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x12, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0xf4, 0x01, 0x0a,
	0x12, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x47, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x61, 0x6e, 0x64,
	0x6c, 0x6f, 0x72, 0x64, 0x73, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x61, 0x74, 0x1a, 0x3b, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x4c, 0x0a, 0x18, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x22, 0x2e, 0x0a, 0x13, 0x4c, 0x61, 0x6e, 0x64,
	0x6c, 0x6f, 0x72, 0x64, 0x73, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x19, 0x4c, 0x61, 0x6e, 0x64,
	0x6c, 0x6f, 0x72, 0x64, 0x73, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x43, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x4c, 0x61, 0x6e, 0x64, 0x6c,
	0x6f, 0x72, 0x64, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0e, 0x4c, 0x61, 0x6e, 0x64, 0x6c,
	0x6f, 0x72, 0x64, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0e, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x50,
	0x6c, 0x61, 0x79, 0x53, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x22, 0x46, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_landlords_proto_rawDescOnce sync.Once
	file_protobuf_landlords_proto_rawDescData = file_protobuf_landlords_proto_rawDesc
)

func file_protobuf_landlords_proto_rawDescGZIP() []byte {
	file_protobuf_landlords_proto_rawDescOnce.Do(func() {
		file_protobuf_landlords_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_landlords_proto_rawDescData)
	})
	return file_protobuf_landlords_proto_rawDescData
}

var file_protobuf_landlords_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protobuf_landlords_proto_goTypes = []interface{}{
	(*LandlordsCreateRoomS)(nil),      // 0: protobuf.LandlordsCreateRoomS
	(*LandlordsCreateRoomC)(nil),      // 1: protobuf.LandlordsCreateRoomC
	(*LandlordsJoinRoomS)(nil),        // 2: protobuf.LandlordsJoinRoomS
	(*LandlordsJoinRoomC)(nil),        // 3: protobuf.LandlordsJoinRoomC
	(*LandlordsJoinRoomNotifyC)(nil),  // 4: protobuf.LandlordsJoinRoomNotifyC
	(*LandlordsLeaveRoomS)(nil),       // 5: protobuf.LandlordsLeaveRoomS
	(*LandlordsLeaveRoomC)(nil),       // 6: protobuf.LandlordsLeaveRoomC
	(*LandlordsLeaveRoomNotifyC)(nil), // 7: protobuf.LandlordsLeaveRoomNotifyC
	(*LandlordsStartGameS)(nil),       // 8: protobuf.LandlordsStartGameS
	(*LandlordsCallS)(nil),            // 9: protobuf.LandlordsCallS
	(*LandlordsPlayS)(nil),            // 10: protobuf.LandlordsPlayS
	(*Card)(nil),                      // 11: protobuf.Card
	nil,                               // 12: protobuf.LandlordsJoinRoomC.UserSeatEntry
}
var file_protobuf_landlords_proto_depIdxs = []int32{
	12, // 0: protobuf.LandlordsJoinRoomC.user_seat:type_name -> protobuf.LandlordsJoinRoomC.UserSeatEntry
	11, // 1: protobuf.LandlordsPlayS.cards:type_name -> protobuf.Card
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_landlords_proto_init() }
func file_protobuf_landlords_proto_init() {
	if File_protobuf_landlords_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_landlords_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsCreateRoomS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsCreateRoomC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsJoinRoomS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsJoinRoomC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsJoinRoomNotifyC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsLeaveRoomS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsLeaveRoomC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsLeaveRoomNotifyC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsStartGameS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsCallS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordsPlayS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_landlords_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_landlords_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_landlords_proto_goTypes,
		DependencyIndexes: file_protobuf_landlords_proto_depIdxs,
		MessageInfos:      file_protobuf_landlords_proto_msgTypes,
	}.Build()
	File_protobuf_landlords_proto = out.File
	file_protobuf_landlords_proto_rawDesc = nil
	file_protobuf_landlords_proto_goTypes = nil
	file_protobuf_landlords_proto_depIdxs = nil
}
