// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: protobuf/message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageID int32

const (
	MessageID_None                       MessageID = 0    // 无
	MessageID_System_Heartbeat           MessageID = 1000 // 心跳
	MessageID_System_ServerTime          MessageID = 1001 // 获取服务器时间 Client: Time
	MessageID_System_Login               MessageID = 1002 // 登录 Server: SystemLoginS Client: SystemLoginC
	MessageID_Landlords_CreateRoom       MessageID = 2000 // 创建房间 Server: LandlordsCreateRoomS Client: LandlordsCreateRoomC
	MessageID_Landlords_JoinRoom         MessageID = 2001 // 加入房间 Server: LandlordsJoinRoomS Client: LandlordsJoinRoomC
	MessageID_Landlords_LeaveRoom        MessageID = 2002 // 离开房间 Server: LandlordsLeaveRoomS Client: LandlordsLeaveRoomC
	MessageID_Landlords_Ready            MessageID = 2003 // 准备 Server: LandlordsReadyS Client: LandlordsReadyC
	MessageID_Landlords_Start            MessageID = 2004 // 开始 Server: LandlordsStartS Client: LandlordsStartC
	MessageID_Landlords_Call             MessageID = 2005 // 叫地主 Server: LandlordsCallS Client: LandlordsCallC
	MessageID_Landlords_CallPass         MessageID = 2006 // 不叫 Server: LandlordsCallPassS Client: LandlordsCallPassC
	MessageID_Landlords_Grab             MessageID = 2007 // 抢地主 Server: LandlordsGrabS Client: LandlordsGrabC
	MessageID_Landlords_GrabPass         MessageID = 2008 // 不抢 Server: LandlordsGrabPassS Client: LandlordsGrabPassC
	MessageID_Landlords_Play             MessageID = 2009 // 出牌 Server: LandlordsPlayS Client: LandlordsPlayC
	MessageID_Landlords_Pass             MessageID = 2010 // 过牌 Server: LandlordsPassS Client: LandlordsPassC
	MessageID_Landlords_End              MessageID = 2011 // 结束 Server: LandlordsEndS Client: LandlordsEndC
	MessageID_Landlords_Notify_JoinRoom  MessageID = 2100 // 通知加入房间 Client: LandlordsNotifyJoinRoomC
	MessageID_Landlords_Notify_LeaveRoom MessageID = 2101 // 通知离开房间 Client: LandlordsNotifyLeaveRoomC
)

// Enum value maps for MessageID.
var (
	MessageID_name = map[int32]string{
		0:    "None",
		1000: "System_Heartbeat",
		1001: "System_ServerTime",
		1002: "System_Login",
		2000: "Landlords_CreateRoom",
		2001: "Landlords_JoinRoom",
		2002: "Landlords_LeaveRoom",
		2003: "Landlords_Ready",
		2004: "Landlords_Start",
		2005: "Landlords_Call",
		2006: "Landlords_CallPass",
		2007: "Landlords_Grab",
		2008: "Landlords_GrabPass",
		2009: "Landlords_Play",
		2010: "Landlords_Pass",
		2011: "Landlords_End",
		2100: "Landlords_Notify_JoinRoom",
		2101: "Landlords_Notify_LeaveRoom",
	}
	MessageID_value = map[string]int32{
		"None":                       0,
		"System_Heartbeat":           1000,
		"System_ServerTime":          1001,
		"System_Login":               1002,
		"Landlords_CreateRoom":       2000,
		"Landlords_JoinRoom":         2001,
		"Landlords_LeaveRoom":        2002,
		"Landlords_Ready":            2003,
		"Landlords_Start":            2004,
		"Landlords_Call":             2005,
		"Landlords_CallPass":         2006,
		"Landlords_Grab":             2007,
		"Landlords_GrabPass":         2008,
		"Landlords_Play":             2009,
		"Landlords_Pass":             2010,
		"Landlords_End":              2011,
		"Landlords_Notify_JoinRoom":  2100,
		"Landlords_Notify_LeaveRoom": 2101,
	}
)

func (x MessageID) Enum() *MessageID {
	p := new(MessageID)
	*p = x
	return p
}

func (x MessageID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageID) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_message_proto_enumTypes[0].Descriptor()
}

func (MessageID) Type() protoreflect.EnumType {
	return &file_protobuf_message_proto_enumTypes[0]
}

func (x MessageID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageID.Descriptor instead.
func (MessageID) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   MessageID `protobuf:"varint,1,opt,name=id,proto3,enum=protobuf.MessageID" json:"id,omitempty"`
	Body []byte    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() MessageID {
	if x != nil {
		return x.Id
	}
	return MessageID_None
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_protobuf_message_proto protoreflect.FileDescriptor

var file_protobuf_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x42, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0xac, 0x03, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x10, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x10, 0xe8, 0x07, 0x12, 0x16, 0x0a, 0x11, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x10, 0xe9, 0x07, 0x12, 0x11, 0x0a,
	0x0c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0xea, 0x07,
	0x12, 0x19, 0x0a, 0x14, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0xd0, 0x0f, 0x12, 0x17, 0x0a, 0x12, 0x4c,
	0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x10, 0xd1, 0x0f, 0x12, 0x18, 0x0a, 0x13, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64,
	0x73, 0x5f, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0xd2, 0x0f, 0x12, 0x14,
	0x0a, 0x0f, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x10, 0xd3, 0x0f, 0x12, 0x14, 0x0a, 0x0f, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64,
	0x73, 0x5f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0xd4, 0x0f, 0x12, 0x13, 0x0a, 0x0e, 0x4c, 0x61,
	0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x43, 0x61, 0x6c, 0x6c, 0x10, 0xd5, 0x0f, 0x12,
	0x17, 0x0a, 0x12, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x43, 0x61, 0x6c,
	0x6c, 0x50, 0x61, 0x73, 0x73, 0x10, 0xd6, 0x0f, 0x12, 0x13, 0x0a, 0x0e, 0x4c, 0x61, 0x6e, 0x64,
	0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x47, 0x72, 0x61, 0x62, 0x10, 0xd7, 0x0f, 0x12, 0x17, 0x0a,
	0x12, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x47, 0x72, 0x61, 0x62, 0x50,
	0x61, 0x73, 0x73, 0x10, 0xd8, 0x0f, 0x12, 0x13, 0x0a, 0x0e, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f,
	0x72, 0x64, 0x73, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x10, 0xd9, 0x0f, 0x12, 0x13, 0x0a, 0x0e, 0x4c,
	0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x50, 0x61, 0x73, 0x73, 0x10, 0xda, 0x0f,
	0x12, 0x12, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x45, 0x6e,
	0x64, 0x10, 0xdb, 0x0f, 0x12, 0x1e, 0x0a, 0x19, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64,
	0x73, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x10, 0xb4, 0x10, 0x12, 0x1f, 0x0a, 0x1a, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64,
	0x73, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x10, 0xb5, 0x10, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_message_proto_rawDescOnce sync.Once
	file_protobuf_message_proto_rawDescData = file_protobuf_message_proto_rawDesc
)

func file_protobuf_message_proto_rawDescGZIP() []byte {
	file_protobuf_message_proto_rawDescOnce.Do(func() {
		file_protobuf_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_message_proto_rawDescData)
	})
	return file_protobuf_message_proto_rawDescData
}

var file_protobuf_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_message_proto_goTypes = []interface{}{
	(MessageID)(0),  // 0: protobuf.MessageID
	(*Message)(nil), // 1: protobuf.Message
}
var file_protobuf_message_proto_depIdxs = []int32{
	0, // 0: protobuf.Message.id:type_name -> protobuf.MessageID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_message_proto_init() }
func file_protobuf_message_proto_init() {
	if File_protobuf_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_message_proto_goTypes,
		DependencyIndexes: file_protobuf_message_proto_depIdxs,
		EnumInfos:         file_protobuf_message_proto_enumTypes,
		MessageInfos:      file_protobuf_message_proto_msgTypes,
	}.Build()
	File_protobuf_message_proto = out.File
	file_protobuf_message_proto_rawDesc = nil
	file_protobuf_message_proto_goTypes = nil
	file_protobuf_message_proto_depIdxs = nil
}
