// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: protobuf/time.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Time struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unix int64 `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
}

func (x *Time) Reset() {
	*x = Time{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_time_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_time_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_protobuf_time_proto_rawDescGZIP(), []int{0}
}

func (x *Time) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

type PeriodTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartUnix int64 `protobuf:"varint,1,opt,name=start_unix,json=startUnix,proto3" json:"start_unix,omitempty"`
	EndUnix   int64 `protobuf:"varint,2,opt,name=end_unix,json=endUnix,proto3" json:"end_unix,omitempty"`
}

func (x *PeriodTime) Reset() {
	*x = PeriodTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_time_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeriodTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodTime) ProtoMessage() {}

func (x *PeriodTime) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_time_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodTime.ProtoReflect.Descriptor instead.
func (*PeriodTime) Descriptor() ([]byte, []int) {
	return file_protobuf_time_proto_rawDescGZIP(), []int{1}
}

func (x *PeriodTime) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *PeriodTime) GetEndUnix() int64 {
	if x != nil {
		return x.EndUnix
	}
	return 0
}

var File_protobuf_time_proto protoreflect.FileDescriptor

var file_protobuf_time_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0x1a, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x78, 0x22, 0x46, 0x0a, 0x0a, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x55,
	0x6e, 0x69, 0x78, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_time_proto_rawDescOnce sync.Once
	file_protobuf_time_proto_rawDescData = file_protobuf_time_proto_rawDesc
)

func file_protobuf_time_proto_rawDescGZIP() []byte {
	file_protobuf_time_proto_rawDescOnce.Do(func() {
		file_protobuf_time_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_time_proto_rawDescData)
	})
	return file_protobuf_time_proto_rawDescData
}

var file_protobuf_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_time_proto_goTypes = []interface{}{
	(*Time)(nil),       // 0: protobuf.Time
	(*PeriodTime)(nil), // 1: protobuf.PeriodTime
}
var file_protobuf_time_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_time_proto_init() }
func file_protobuf_time_proto_init() {
	if File_protobuf_time_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_time_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Time); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_time_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeriodTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_time_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_time_proto_goTypes,
		DependencyIndexes: file_protobuf_time_proto_depIdxs,
		MessageInfos:      file_protobuf_time_proto_msgTypes,
	}.Build()
	File_protobuf_time_proto = out.File
	file_protobuf_time_proto_rawDesc = nil
	file_protobuf_time_proto_goTypes = nil
	file_protobuf_time_proto_depIdxs = nil
}
